version: '3'

tasks:
  develop:
    cmds:
      - cmd: nvm use
      - cmd: npm install
  ios:
    cmds:
      - cmd: npm run ios
  xcode:
    cmds:
      - cmd: echo export NODE_BINARY=$(command -v node) > ios/.xcode.env
      - cmd: open ios/directory.xcworkspace
